# Use custom dev environment with Cypress runtime support
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Startup Task
    init: yarn install # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: yarn exec nx preview demo

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 4300 for the frontend
    port: 4300
    onOpen: open-preview
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
